In [1]:
import tensorflow

In [1]:
import cv2

In [2]:
from keras.preprocessing import image

In [3]:
import os

In [4]:
categories=["with_mask","without_mask"]

In [8]:
data=[]

for category in categories:
    
    path = os.path.join('dataset',category)
    
    label=categories.index(category)
    
    print(label)
    
    for file in os.listdir(path):
        
        img_path = os.path.join(path,file)
        
        img = cv2.imread(img_path)
        
          
        img = cv2.resize(img,(224,224))
        
        data.append([img,label])
 

0
1


In [7]:
data[0]

[array([[[18, 40, 45],
         [20, 40, 45],
         [19, 40, 42],
         ...,
         [23, 37, 35],
         [24, 38, 36],
         [23, 37, 35]],
 
        [[19, 41, 46],
         [21, 41, 46],
         [19, 40, 42],
         ...,
         [24, 38, 36],
         [24, 38, 36],
         [23, 37, 35]],
 
        [[20, 42, 47],
         [21, 41, 46],
         [19, 40, 42],
         ...,
         [25, 39, 37],
         [25, 39, 37],
         [24, 38, 36]],
 
        ...,
 
        [[66, 74, 64],
         [68, 76, 66],
         [70, 78, 68],
         ...,
         [74, 82, 85],
         [74, 81, 84],
         [74, 81, 84]],
 
        [[65, 73, 63],
         [67, 75, 65],
         [69, 77, 67],
         ...,
         [82, 89, 92],
         [81, 88, 91],
         [80, 87, 90]],
 
        [[65, 73, 63],
         [67, 75, 65],
         [69, 77, 67],
         ...,
         [87, 94, 97],
         [86, 93, 96],
         [85, 92, 95]]], dtype=uint8),
 0]

In [9]:
import random

In [10]:
random.shuffle(data)

In [11]:
X = []
y = []

for features,labels in data:
    
    X.append(features)
    
    y.append(labels)

In [14]:
X[0]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [16]:
import numpy as np

In [17]:
X = np.array(X)

y = np.array(y)

In [18]:
X.shape

(1508, 224, 224, 3)

In [19]:
y

array([0, 0, 0, ..., 0, 0, 1])

In [20]:
X = X/255

In [21]:
X[0]

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [24]:
from keras.applications.vgg16 import VGG16

In [25]:
vgg = VGG16()

In [26]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [27]:
from keras import Sequential

In [28]:
model = Sequential()

In [29]:
for layer in vgg.layers[:-1]:
    
    model.add(layer)

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [31]:
for layer in model.layers:
    
    layer.trainable = False

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [33]:
from keras.layers import Dense

In [34]:
model.add(Dense(1,activation='sigmoid'))

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [36]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [37]:
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
38/38 [==============================] - 422s 11s/step - loss: 0.5731 - accuracy: 0.6857 - val_loss: 0.3943 - val_accuracy: 0.8775
Epoch 2/5
38/38 [==============================] - 399s 11s/step - loss: 0.3648 - accuracy: 0.8665 - val_loss: 0.2869 - val_accuracy: 0.9139
Epoch 3/5
38/38 [==============================] - 398s 11s/step - loss: 0.2614 - accuracy: 0.9237 - val_loss: 0.2287 - val_accuracy: 0.9371
Epoch 4/5
38/38 [==============================] - 394s 10s/step - loss: 0.2214 - accuracy: 0.9411 - val_loss: 0.1976 - val_accuracy: 0.9371
Epoch 5/5
38/38 [==============================] - 397s 10s/step - loss: 0.1921 - accuracy: 0.9527 - val_loss: 0.1808 - val_accuracy: 0.9470


In [77]:
cap = cv2.VideoCapture(0)

In [76]:
while True:
    
    ret, frame = cap.read()
    
    # call detection function
    
    
    
    img = cv2.resize(frame,(224,224))
    
   
    
    y_pred = detect_face_mask(img)
    
    print(y_pred)
    
    if y_pred == 0:
        
        draw_label(frame,"Mask",(30,30),(0,255,0))
        
    else:
        draw_label(frame,"No Mask",(30,30),(0,0,255))
        
    
    
    
    cv2.imshow("window",frame)
    
    if cv2.waitKey(1) & 0xFF == ord('x'):
        break
        
cv2.destroyAllWindows()

1/1 [==============================] - 0s 412ms/step
1
1/1 [==============================] - 0s 400ms/step
1
1/1 [==============================] - 0s 388ms/step
1
1/1 [==============================] - 0s 382ms/step
1
1/1 [==============================] - 0s 381ms/step
1
1/1 [==============================] - 0s 376ms/step
1
1/1 [==============================] - 0s 374ms/step
1
1/1 [==============================] - 0s 377ms/step
1
1/1 [==============================] - 0s 379ms/step
1
1/1 [==============================] - 0s 375ms/step
1
1/1 [==============================] - 0s 377ms/step
1
1/1 [==============================] - 0s 380ms/step
1
1/1 [==============================] - 0s 379ms/step
1
1/1 [==============================] - 0s 383ms/step
1
1/1 [==============================] - 0s 380ms/step
0
1/1 [==============================] - 0s 377ms/step
0
1/1 [==============================] - 0s 381ms/step
0
1/1 [==============================] - 0s 374ms/step
0
1/1 [=====

In [65]:
def detect_face_mask(img):
    y_pred=model.predict(img.reshape(1,224,224,3))
    
    y_pred1 = []
    for element in y_pred:
        if element > 0.5:
            y_pred1.append(1)
        else:
            y_pred1.append(0)
    
    return y_pred1[0]

In [67]:
def draw_label(img,text,pos,bg_color):
    
    text_size = cv2.getTextSize(text,cv2.FONT_HERSHEY_SIMPLEX,1,cv2.FILLED)
    
    end_x = pos[0] + text_size[0][0] + 2
    end_y = pos[1] + text_size[0][1] - 2
    
    cv2.rectangle(img,pos,(end_x,end_y),bg_color,cv2.FILLED)
    
    cv2.putText(img,text,pos,cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),1,cv2.LINE_AA)